development:
  bucket: BabyFolio
  access_key_id: AKIAJX5WFA27ACV24IPQ
  secret_access_key: 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
test:
  bucket: BabyFolio
  access_key_id: AKIAJX5WFA27ACV24IPQ
  secret_access_key: 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
production:  
  bucket: babyfolio-production
  access_key_id: AKIAIKSH5IFPRA25HIHA
  secret_access_key: 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