default:
  theme_advanced_toolbar_align: left
  theme_advanced_buttons3_add:
    - tablecontrols
  plugins:
    - table

page_edit:
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_buttons3: ""
  theme_advanced_buttons2: ""
  theme_advanced_buttons1:
    - fontselect
    - fontsizeselect
    - forecolorpicker
    - separator
    - bold
    - italic
    - underline
    - separator
    - link
    - unlink
    - separator
    - code
    
    
  theme_advanced_fonts:
    - "Arvo Regular=ArvoRegular"
    - "Arvo Italic=ArvoItalic"
    - "Arvo Bold=ArvoBold"
    - "Arvo Bold=Italic"
    - "Arial=arial,helvetica,sans-serif"
    - "Georgia=georgia,palatino;"
    - "Helvetica=helvetica;"
    - "Times New Roman=times new roman,times;"
    - "Verdana=verdana,geneva;"
  
    

