defaults: &defaults

  youtube:
    key: "821905120152.apps.googleusercontent.com"
    secret: "q9XDXCtGECoa0clbFMeVGuKT"
    dev_key: "AI39si5CBu2pCYdFlu9nRI5ATwxqvUHm3vlw2MR4qD42DjXRS-UkGhXhai1oT7V4DBt8OJmQn9h6qzfX7OsggfcMf-8luMew4w"

  flickr:
    key: "711439ce527642e0fee2d5fc76f2affe"
    secret: "d0b79889905ec211"

  facebook:
    key: "263019473774028"
    secret: "7c92fcaf00c30a9da772af2de7a2b144"

  vimeo:
    key: "469d0a2c5142412c29dcd41193f6b10a"
    secret: "403e3bdb5a50b9bf"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults